# Generated by Django 4.0.4 on 2022-06-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='can_set_price',
            field=models.BooleanField(default=False),
        ),
    ]
