# Generated by Django 4.0.4 on 2022-05-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='credit',
        ),
    ]
