# Generated by Django 4.0.4 on 2022-05-19 10:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customerprofile_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='item',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='volume',
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.item')),
            ],
        ),
    ]
