# Generated by Django 4.0.4 on 2022-06-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_invoice_item_remove_invoice_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='customer_type',
        ),
        migrations.DeleteModel(
            name='CustomerType',
        ),
    ]
