# Generated by Django 4.0.4 on 2022-06-01 10:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='post',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='zip_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
