# Generated by Django 4.0.4 on 2022-05-06 17:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='zip_code',
            field=models.BigIntegerField(blank=True),
        ),
    ]
