# Generated by Django 4.0.4 on 2022-05-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_invoice_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='credit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
