# Generated by Django 4.0.4 on 2022-05-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_remove_memberprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='zip_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
