# Generated by Django 4.0.4 on 2022-05-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_invoice_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='credit',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='credit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
