# Generated by Django 4.0.4 on 2022-05-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_remove_invoice_approved_invoice_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='approval_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
